version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "app/yarn.lock" }}
  build_and_push_image:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install aws cli
          command: |
            apk add --no-cache --update py-pip
            pip install awscli
      - run:
          name: build image
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker build -t ${ECR_REPO_URI}:$CIRCLE_SHA1 -t ${ECR_REPO_URI}:latest .
      - run:
          name: push image
          command: |
            docker push ${ECR_REPO_URI}:$CIRCLE_SHA1
            docker push ${ECR_REPO_URI}:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  deploy_production:
    jobs:
      - build:
          filters:
            branches:
              only: [production]
      - build_and_push_image:
          requires: [build]

